Quiz complete
elie-prbl/front pull request #25
Opened 2024-06-23 14:28 UTC by PaulGeneve

2024-06-23 19:32 UTC, LenaPancher requested changes

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizSlices.ts
> +	extraReducers: (builder) => {
Fix lint

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizSlices.ts
> +			.addCase(getUserQuiz.pending, (state) => {
Fix lint

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizSlices.ts
> +			.addCase(submitUserQuiz.pending, (state) => {
Fix lint

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizSlices.ts
> +				// @ts-ignore
A supprimer après le changement du `initialState`

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizSlices.ts
> +				// @ts-ignore
A supprimer après le changement du `initialState`

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizSlices.ts
Petite question, ce fichier n'est pas utilisé ? Il sert à quoi réellement ?

2024-06-23 19:32 UTC, LenaPancher commented on src/views/game/Game.tsx
> +import {getUserQuiz} from "../../store/features/UserQuiz/UserQuizThunk";
Fix lint

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizThunk.ts
> +export const getUserQuiz = createAsyncThunk("getUserQuiz", async (userId, { rejectWithValue }) => {
```suggestion
export const getUserQuiz = createAsyncThunk("getUserQuiz", async (userId: string, { rejectWithValue }) => {
```

2024-06-23 19:32 UTC, LenaPancher commented on src/store/features/UserQuiz/UserQuizThunk.ts
> +	const response = await fetch(`${Url.BASE_URL_API}/games/quiz/6`, {
```suggestion
	const response = await fetch(`${Url.BASE_URL_API}/games/quiz/${userId}`, {
```

2024-06-24 09:07 UTC, PaulGeneve commented on src/store/features/UserQuiz/UserQuizSlices.ts
à la base c'etait pour gerer les etat des requetes mais c'est vrai que j'avais pas vu que je l'utilisais plus

2024-06-24 14:07 UTC, robLittiere requested changes

2024-06-24 14:07 UTC, robLittiere commented on src/base/constant.tsx
> +	static BASE_URL_WS: string = `ws://${Url.IP}:7070/ws`;
Ces changements ne devraient pas être commité car c'est la configuration locale

2024-06-26 08:55 UTC, LenaPancher reviewed
Penses à supprimer tes imports non utilisés, et il faut fixer les lint. 

Dans le composant `QuestComponent`, à la ligne 16, rajoutes `isNext` dans `CircleComponent`.

2024-06-26 08:55 UTC, LenaPancher commented on src/views/Home.tsx
> -				dispatch(setPosition({ latitude, longitude }));
Il ne faut pas supprimer ce code là, ça permet d'avoir la localisation de l'utilisateur ! Recrée un useEffect avec ta méthode.

2024-06-26 08:55 UTC, LenaPancher commented on src/components/game/GameHomeComponent.tsx
> +	nextQuiz: string[];
Juste `string` ça suffit, pas besoin que se soit un tableau de string, on va recevoir juste un quiz, pas plusieurs. Donc des changements sont nécessaires dans `Home`.

2024-06-26 08:55 UTC, LenaPancher commented on src/views/Home.tsx
> +	const [nextQuizzes, setNextQuizzes] = React.useState<string[]>([]);
```suggestion
	const [nextQuiz, setNextQuiz] = React.useState<string>("");
```

2024-06-26 08:55 UTC, LenaPancher commented on src/views/Home.tsx
> +				setNextQuizzes(response.nextQuiz.title ? response.nextQuiz.title : []);
```suggestion
				setNextQuiz(response.nextQuiz.title ? response.nextQuiz.title : "");
```

2024-06-26 08:55 UTC, LenaPancher commented on src/views/Home.tsx
> +					<GameHomeComponent nextQuiz={nextQuizzes} />
A remplacer par `nextQuiz`

2024-06-26 08:55 UTC, LenaPancher commented on src/views/game/Game.tsx
> +	}, [dispatch]);
Pas besoin de cette méthode, avec la ligne 35 tu récupères déjà ton user, donc tu as assez à son `uuid`.

2024-06-26 08:55 UTC, LenaPancher commented on src/views/game/Game.tsx
> +	}, [dispatch, user!.uuid]);
Pas nécessaire

2024-06-26 08:55 UTC, LenaPancher commented on src/views/game/GameQuiz.tsx
> +
Pas nécessaire, ta ligne 44 suffit

2024-06-26 08:58 UTC, LenaPancher commented on src/views/game/Game.tsx
> +							// @ts-ignore
T'es pas censé ajouter `// @ts-ignore`, si il y a un problème faut pas l'ignorer, idem pour la ligne 126

2024-06-26 09:08 UTC, LenaPancher commented on src/views/game/Game.tsx
> +	const [completedQuizzes, setCompletedQuizzes] = useState<number[]>([]);
Pour éviter le `@ts-ignore` : 
```suggestion
	const [completedQuizzes, setCompletedQuizzes] = useState<string[]>([]);
```

2024-06-26 09:51 UTC, merged